services:
  app:
    build:
      context: .
      args:
        HOST_LAN_IP: ${HOST_LAN_IP}
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - turn

  turn:
    image: instrumentisto/coturn
    network_mode: host
    command: >
      --no-dtls --no-tls --verbose
      --lt-cred-mech
      --user=user:pass
      --realm=localhost
      --listening-port=3478
      --log-file=./turn.log
