networks:
  appnet:
    driver: bridge
services:
  app:
    build:
      context: .
      args:
        HOST_LAN_IP: ${HOST_LAN_IP}
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - turn
    networks:
      - appnet

  turn:
    image: instrumentisto/coturn
    # network_mode: host !!!THIS FOR MAC ONLY!!!
    command: >
      --no-dtls --no-tls --verbose
      --lt-cred-mech
      --user=user:pass
      --realm=turn
      --listening-port=3478
      --log-file=./turn.log
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    networks:
      - appnet
